from apps.shop.admin.BrandAdmin import *
from apps.shop.admin.CategoryAdmin import *
from apps.shop.admin.CompanyAdmin import *
from apps.shop.admin.DiscountAdmin import *
from apps.shop.admin.OrderProductAdmin import *
from apps.shop.admin.PaymentMethodAdmin import *
from apps.shop.admin.ProductAdmin import *
from apps.shop.admin.ProductDiscountAdmin import *
from apps.shop.admin.ProductPhotoAdmin import *
from apps.shop.admin.PurchaseOrderAdmin import *
from apps.shop.admin.ReviewAdmin import *
from apps.shop.admin.ShoppingCartAdmin import *
from apps.shop.admin.ShoppingCartProductAdmin import *